import { TitleSlide } from './TitleSlide';
import { StarWarsCrawlSlide1 } from './StarWarsCrawlSlide1';
import { StarWarsCrawlSlide2 } from './StarWarsCrawlSlide2';
import { StarWarsCrawlSlide3 } from './StarWarsCrawlSlide3';
import { StarWarsCrawlSlide4 } from './StarWarsCrawlSlide4';
import { StarWarsCrawlSlide5 } from './StarWarsCrawlSlide5';
import { StarWarsCrawlSlide6 } from './StarWarsCrawlSlide6';
import { StarWarsCrawlSlide7 } from './StarWarsCrawlSlide7';
import { StarWarsCrawlSlide8 } from './StarWarsCrawlSlide8';
import { BioSlide } from './BioSlide';
import { JuniorEngineerSlide } from './JuniorEngineerSlide';
import { VibeFlowStepsSlide } from './VibeFlowStepsSlide';
import { MarketplacesSlide } from './MarketplacesSlide';
import { BreakOutOfCodingSlide } from './BreakOutOfCodingSlide';
import { ClaudeCodeSlide } from './ClaudeCodeSlide';
import { OneMoreTipSlide } from './OneMoreTipSlide';
import { WhatIsSkillSlide } from './WhatIsSkillSlide';
import { LifeAfterCommitSlide } from './LifeAfterCommitSlide';
import { FinalSlide } from './FinalSlide';

export const slides = [TitleSlide, StarWarsCrawlSlide1, BioSlide, StarWarsCrawlSlide2, JuniorEngineerSlide, StarWarsCrawlSlide3, VibeFlowStepsSlide, StarWarsCrawlSlide4, BreakOutOfCodingSlide, LifeAfterCommitSlide, ClaudeCodeSlide, StarWarsCrawlSlide5, OneMoreTipSlide, StarWarsCrawlSlide6, WhatIsSkillSlide, StarWarsCrawlSlide7, MarketplacesSlide, StarWarsCrawlSlide8, FinalSlide];
